FROM elasticsearch:1.7

RUN /usr/share/elasticsearch/bin/plugin -install elastic/elasticsearch-cloud-aws/2.7.1
RUN /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head

# COPY config/ /usr/share/elasticsearch/config/
